version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
  demoapp:
    depends_on:
      - db
    image: my-registry:50000/buddzbuddy/demoapp:build-8
  integration:
    depends_on:
      - demoapp
    image: my-registry:50000/buddzbuddy/demoapp:test
    build:
      context: .
      dockerfile: Dockerfile.Integration
      
volumes:
    dbdata: