FROM mcr.microsoft.com/dotnet/sdk:6.0

WORKDIR /home/app

COPY ./*.sln ./
COPY ./*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ./${file%.*}/ && mv $file ./${file%.*}/; done

RUN dotnet restore

COPY . .

WORKDIR /home/app/Integration/

ENTRYPOINT ["dotnet", "test"]